### ISSUE TITLE
'gmssl.func' has no 'str_to_list' member

### ISSUE THREAD

**Issue by L1v1T** [gongxian-ding/gmssl-python#2]

**Comment by L1v1T** [comment]
测试文件 'tests/test_sm3.py' 中使用的 'func.str_to_list' 没有在 'func.py' 里实现。

**Comment by datouguo** [comment]
请移步 https://github.com/duanhongyi/gmssl  ，使用y = sm3.sm3_hash(func.bytes_to_list(b"abc")) 测试。

**Comment by gongxian-ding** [comment]
它已在最新更新中修复。
